name: PHPCS

on:
  push:
  pull_request:

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: none
      - name: Install dependencies
        run: composer install --no-progress --prefer-dist
      - name: Run PHPCS
        run: composer phpcs
